CREATE TABLE IF NOT EXISTS hotel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    stars INT NOT NULL CHECK (stars >= 1 AND stars <= 5),
    description TEXT
);

CREATE TABLE IF NOT EXISTS room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(10) NOT NULL,
    type VARCHAR(50) NOT NULL, -- (ej: SINGLE, DOUBLE, SUITE)
    price_per_night DECIMAL(10, 2) NOT NULL,
    hotel_id BIGINT NOT NULL, -- <-- La clave foránea
    CONSTRAINT fk_hotel FOREIGN KEY (hotel_id) REFERENCES hotel(id) -- <-- La restricción
);